# This is a basic workflow to help you get started with Actions

name: Sync Fork
on:
  schedule:
    - cron: '*/10 * * * *' # every 30 minutes
  workflow_dispatch: # on button click
  push:
    branches: [ "main" ]
jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.KR }}
          upstream_repository: KingRan/KR
          target_repository: nzmd/KR
          upstream_branch: main
          target_branch: main
          force: true
          tags: true
