# This is a basic workflow to help you get started with Actions

name: CI
on: push
jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: KingRan/KR
          target_repository: nzmd/KR
          upstream_branch: main
          target_branch: main
          force: true
          tags: true
